### ISSUE TITLE
[BUG] Unable to run provided example script inference_json.py

### ISSUE THREAD

**Issue by ramakrishnaniyer** [turboderp/exllamav2#626]
### OS

Linux

### GPU Library

CUDA 12.x

### Python version

3.12

### Pytorch version

2.4.1

### Describe the bug

Unable to run the provided example script 'inference_json.py'. 
Executing the script (after setting paged=False when initializing the generator; I am unable to use flash attention) results in Attribute Error: 'ExLLamaV2TokenEnforcerFilter' object has no attribute 'background_drop'. 
Please note that I had no issues running the previous provided example 'inference.py' with the same settings for the generator. 

### Reproduction steps

Installed exllamav2 via pip install per the documentation and tried to execute provided example scripts inference.py and inference_json.py. Downloaded mistral-7b-exl2/4.0bpw model from Hugging Face

### Expected behavior

Successful execution without the above error. 

### Acknowledgements

- [X] I have looked for similar issues before submitting this one.
- [X] I understand that the developers have lives and my issue will be answered when possible.
- [X] I understand the developers of this program are human, and I will ask my questions politely.

**Comment by kokoabear** [comment]
I'm having a similar issue:

```Answer, With JSON schema enforcing:
Traceback (most recent call last):
  File "C:\Users\xx\Desktop\CODING\yy\main.py", line 52, in <module>
    result = exllamav2_with_format_enforcer(question_with_schema, parser=parser)
  File "C:\Users\xx\Desktop\CODING\yy\main.py", line 40, in exllamav2_with_format_enforcer
    result = generator.generate_simple(prompt, settings, num_tokens=150, seed=1234, filters=filters) #max_new_tokens=150,
  File "C:\Users\xx\Desktop\CODING\yy\venv\lib\site-packages\exllamav2\generator\base.py", line 268, in generate_simple
    ExLlamaV2Sampler.sample(
  File "C:\Users\xx\Desktop\CODING\yy\venv\lib\site-packages\exllamav2\generator\sampler.py", line 405, in sample
    pt, et = f.get_next()
AttributeError: 'ExLlamaV2TokenEnforcerFilter' object has no attribute 'get_next'```

**Comment by turboderp** [comment]
Have you pulled the latest changes to the master branch? There was an issue with the ExLlamaV2 integration in because it isn't inheriting the base filter class, so I added [this wrapper](https://github.com/turboderp/exllamav2/blob/master/examples/inference_json_lmfe_wrapper.py) instead. This didn't make it into the 0.2.2 release files, though, but the example code from master should still work with 0.2.2.

**Comment by ramakrishnaniyer** [comment]
Thank you for your prompt response and help! I have been working with 0.2.1.  
Could you please let me know when 0.2.2 will be available via PyPI? My workflow constrains it so that pip installing via PyPI is  optimal.

**Comment by turboderp** [comment]
Oops, I just forgot to push it to PyPi. It's available now.

**Comment by ramakrishnaniyer** [comment]
Upgraded to 0.2.2 from PyPI, but now when I run 'inference_json.py', I am getting "ModuleNotFoundError: No module named 'inference_json_lmfe_wrapper' ". Would appreciate your help with getting this fixed, thanks!

**Comment by turboderp** [comment]
inference_json_lmfe_wrapper.py is in the same folder. [Here.](https://github.com/turboderp/exllamav2/tree/master/examples) Something up with your path I guess. You can also just copy the code into inference_json.py I guess.

**Comment by ramakrishnaniyer** [comment]
Issue is resolved following your suggestion to copy code into inference_json.py. I will check out the path issue at my end. Thank you so much for your prompt help with this.
